### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by charliewilco**
- Drops gulp dependency in favor of npm scripts + config files
- Updates dependencies
- Updates linting rules
- Uses index files to import
- Imports normalize.css from npm

### CODE REVIEW

**Comment by colepeters** [comment]
Thanks for this @charlespeters! I’m really liking these updates. Much leaner than before (I’d been wanting to move to npm scripts for awhile, this is a nice introduction), and great use of some of the nicer postcss-related features.

Would you mind having a go at updating the readme to clarify some of these updates? Primarily [the Development](https://github.com/colepeters/gemma#development) section as it still references gulp, gulp-postcss, etc.

I’ll handle updating the version and publishing to npm once this is done and merged.

**Comment by charliewilco** [comment]
no problem!

**Comment by charliewilco** [comment]
that second commit adds gemma to this cdn https://unpkg.com/gemma (formerly called npmcdn) after you run `npm publish` and specifies the source file for a bundler (so you can override variables when you're adding into a different project)

**Comment by colepeters** [comment]
Looks great, Charles. Thanks again! Merging.

**Pull request merged**
