### PR TITLE
Better the README.md

### PR DESCRIPTION
**Pull request by notenociz**
- Adds the pronunciation (/ˈdʒɛmə/).
- Fixes @mrmrs website from .io (for open source) to .cc (used for all projects)
- Fixes @necolas from GitHub page to website
- Adds @csswizardry (Harry Roberts, maker of ITCSS)

### CODE REVIEW

**Comment by mrmrs** [comment]
I'd rather it link to my open source website - but thanks for the consideration.

**Comment by notenociz** [comment]
@mrmrs — done

**Comment by colepeters** [comment]
Wow, I wasn’t expecting a pull request so soon. Good updates, though — thanks.

**Comment by notenociz** [comment]
It's never too early. Can't wait for more development however. I'm still eager to know what this is exactly. I'm also liking the name, good choice.

**Pull request merged**
